

### Signup / Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "te",
  "lastName": "Wu",
  "email": "te@wu.pl",
  "password": "test12345"
}

### Login
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "jackson.moore@email.com",
  "password": "test12345"
}

### Create a booking
POST http://localhost:8000/api/v1/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRhMmEwYjhmLWM1YzEtNGM2NS05YWJmLTEyZDhhM2Q0NmUyYiIsImlhdCI6MTcwMzQxOTU3MCwiZXhwIjoxNzAzNTA1OTcwfQ.IXT5kkfDXjGPzrDe8_vx9cbkr7pf7C09oJTxizuVVd4

{
  "userId": "4a2a0b8f-c5c1-4c65-9abf-12d8a3d46e2b",
  "tripId": "1",
  "numberOfGuests": 1,
  "guestNames": ["Johnny"],
  "roomType": "single"
}

### Get trips by date range
GET http://localhost:8000/api/v1/trips?startDate=2024-05-01&endDate=2024-10-15
Content-Type: application/json

### Get trip
GET http://localhost:8000/api/v1/trips/1
Content-Type: application/json

