

### Signup / Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "te",
  "lastName": "Wu",
  "email": "te@wu.pl",
  "password": "test12345"
}

### Login Jackson Moore
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "jackson.moore@email.com",
  "password": "test12345"
}

### Login Mia Taylor (owner of booking 012345)
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "mia.taylor@email.com",
  "password": "test12345"
}

### Logout
POST http://localhost:8000/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRhMmEwYjhmLWM1YzEtNGM2NS05YWJmLTEyZDhhM2Q0NmUyYiIsImlhdCI6MTcwMzgwMTE0OSwiZXhwIjoxNzAzODAxMjA5fQ.yNqoSnajfd_z8kdgUMYafDU_vKG36T1PkSMSeGlML68
### Refresh token
POST http://localhost:8000/api/v1/auth/refresh
Content-Type: application/json

### Create a booking
POST http://localhost:8000/api/v1/bookings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRhMmEwYjhmLWM1YzEtNGM2NS05YWJmLTEyZDhhM2Q0NmUyYiIsImlhdCI6MTcwMzgwMTE0OSwiZXhwIjoxNzAzODAxMjA5fQ.yNqoSnajfd_z8kdgUMYafDU_vKG36T1PkSMSeGlML68

{
  "userId": "4a2a0b8f-c5c1-4c65-9abf-12d8a3d46e2b",
  "tripId": "1",
  "numberOfGuests": 1,
  "guestNames": ["Johnny"],
  "roomType": "single"
}

### GET booking by booking number (Mia Taylor)
GET http://localhost:8000/api/v1/bookings/012345
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFlYTg0YWM0LTYyZGQtNDU5Mi04NzU5LWFhZTdhMDY0ZjZjZiIsImlhdCI6MTcwMzQzNDE4OSwiZXhwIjoxNzAzNTIwNTg5fQ.8fUk4yvsF91aPP-IPJt_Fl0nMmbduCUfoaAiaBCNI3o

### GET user bookings
GET http://localhost:8000/api/v1/users/me/bookings
ontent-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFlYTg0YWM0LTYyZGQtNDU5Mi04NzU5LWFhZTdhMDY0ZjZjZiIsImlhdCI6MTcwMzQzNDk2OSwiZXhwIjoxNzAzNTIxMzY5fQ.i99LCqvY2Tlx97dIKai94iDpSS72ybfuNwrWt2v-SkI

### Get trips by date range
GET http://localhost:8000/api/v1/trips?startDate=2024-05-01&endDate=2024-10-15
Content-Type: application/json

### Get trip
GET http://localhost:8000/api/v1/trips/1
Content-Type: application/json

