

### Signup / Create a new user
POST http://localhost:8000/api/v1/auth/signup
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@email.com",
  "password": "test12345"
}

### Login Jackson Moore
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "jackson.moore@email.com",
  "password": "test12345"
}

### Login Mia Taylor (owner of booking 012345)
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "mia.taylor@email.com",
  "password": "test12345"
}

### Logout
POST http://localhost:8000/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer ADD_TOKEN_HERE

### Refresh token
POST http://localhost:8000/api/v1/auth/refresh
Content-Type: application/json

### Create a booking
POST http://localhost:8000/api/v1/bookings
Content-Type: application/json
Authorization: Bearer ADD_TOKEN_HERE

{
  "userId": "4a2a0b8f-c5c1-4c65-9abf-12d8a3d46e2b",
  "tripId": "2",
  "numberOfGuests": 1,
  "guestNames": ["Johnny"],
  "roomType": "single"
}

### GET booking by booking number (Mia Taylor)
GET http://localhost:8000/api/v1/bookings/8M5538EA13
Content-Type: application/json
Authorization: Bearer ADD_TOKEN_HERE

### GET user bookings
GET http://localhost:8000/api/v1/users/me/bookings
ontent-Type: application/json
Authorization: Bearer 

### Get trips by date range
GET http://localhost:8000/api/v1/trips?startDate=2024-05-01&endDate=2024-10-15
Content-Type: application/json

### Get trip
GET http://localhost:8000/api/v1/trips/1
Content-Type: application/json


